"""empty message

Revision ID: 1b1ffadc4c37
Revises: e8cf1c35a84e
Create Date: 2017-12-19 16:19:32.184762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b1ffadc4c37'
down_revision = 'e8cf1c35a84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_message', 'num1')
    op.drop_column('user_message', 'num2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('num2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_message', sa.Column('num1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
