"""empty message

Revision ID: 3277de234ac1
Revises: d8630ab22e0a
Create Date: 2017-12-17 17:11:53.024209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3277de234ac1'
down_revision = 'd8630ab22e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fanscount', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('ouxiangcount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ouxiangcount')
    op.drop_column('user', 'fanscount')
    # ### end Alembic commands ###
