"""empty message

Revision ID: 95a55a6272fd
Revises: eb98ae8c42e6
Create Date: 2017-12-19 17:20:05.127554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95a55a6272fd'
down_revision = 'eb98ae8c42e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_message', 'attr2')
    op.drop_column('user_message', 'attr1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_message', sa.Column('attr1', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user_message', sa.Column('attr2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
