"""empty message

Revision ID: c044a61bb891
Revises: c9cf5c5dede9
Create Date: 2017-12-19 14:27:02.047676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c044a61bb891'
down_revision = 'c9cf5c5dede9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('commtnum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'commtnum')
    # ### end Alembic commands ###
