"""empty message

Revision ID: c9cf5c5dede9
Revises: b020bb0c466c
Create Date: 2017-12-18 20:11:25.880618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9cf5c5dede9'
down_revision = 'b020bb0c466c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=150), nullable=False),
    sa.Column('reciever', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=512), nullable=False),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_item_addtime'), 'timeline_item', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_item_addtime'), table_name='timeline_item')
    op.drop_table('timeline_item')
    # ### end Alembic commands ###
